apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: snippets-jupyter
  name: snippets-jupyter
  namespace: snippets-admin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snippets-jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snippets-jupyter
      name: snippets-jupyter
      namespace: snippets-jupyter
    spec:
      containers:
      - args:
        - manage.py
        - shell_plus
        - --notebook
        command:
        - python
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: CDN_URL
          value: https://snippets.cdn.mozilla.net
        - name: CLUSTER_NAME
          value: "oregon-b"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: snippets-admin-secrets
        - name: DEBUG
          value: "False"
        - name: DJANGO_SETTINGS_MODULE
          value: snippets.settings
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: snippets-admin-secrets
        image: mozorg/snippets:jupyter-e2361416
        imagePullPolicy: Always
        name: snippets-jupyter
        resources:
          limits:
            cpu: "4"
            memory: 3200Mi
          requests:
            cpu: 250m
            memory: 300Mi
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
