apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: snippets-prod
    type: web
  name: snippets-prod
  namespace: snippets-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snippets-prod
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snippets-prod
        type: web
      name: snippets-prod
      namespace: snippets-prod
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - command:
          - ./run-prod.sh
        env:
          - name: WSGI_KEEP_ALIVE
            value: "90"
          - name: WSGI_NUM_WORKERS
            value: "2"
          - name: MEDIA_BUNDLES_PREGEN_ROOT
            value: "us-west/bundles-pregen/"
          - name: DEBUG
            value: "False"
          - name: CDN_URL
            value: "https://snippets.cdn.mozilla.net"
          - name: CLUSTER_NAME
            value: "oregon"
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        image: mozmeao/snippets:redirector-1e7907ee
        imagePullPolicy: IfNotPresent
        name: snippets-prod
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /healthz/
            scheme: HTTP
            port: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
