apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: snippets-stage
    type: web
  name: snippets-stage
  namespace: snippets-stage
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snippets-stage
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snippets-stage
        type: web
      name: snippets-stage
      namespace: snippets-stage
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - command:
          - ./bin/run-prod.sh
        env:
           - name: ALLOWED_HOSTS
             value: "*"
           - name: AWS_ACCESS_KEY_ID
             valueFrom:
               secretKeyRef:
                 key: aws-access-key-id
                 name: snippets-stage-secrets
           - name: AWS_S3_HOST
             value: "s3-us-west-2.amazonaws.com"
           - name: AWS_SECRET_ACCESS_KEY
             valueFrom:
               secretKeyRef:
                 key: aws-secret-access-key
                 name: snippets-stage-secrets
           - name: AWS_STORAGE_BUCKET_NAME
             value: "snippets-stage-us-west"
           - name: BUNDLE_BROTLI_COMPRESS
             value: "True"
           - name: CACHE_URL
             valueFrom:
               secretKeyRef:
                 key: cache-url
                 name: snippets-stage-secrets
           - name: CLUSTER_NAME
             value: "oregon"
           - name: CSP_REPORT_ENABLE
             value: "False"
           - name: CSP_REPORT_ONLY
             value: "True"
           - name: DATABASE_URL
             valueFrom:
               secretKeyRef:
                 key: database-url
                 name: snippets-stage-secrets
           - name: DEAD_MANS_SNITCH_UPDATE_JOBS
             valueFrom:
               secretKeyRef:
                 key: dead-mans-snitch-update-jobs
                 name: snippets-stage-secrets
           - name: DEAD_MANS_SNITCH_PRODUCT_DETAILS
             valueFrom:
               secretKeyRef:
                 key: dead-mans-snitch-product-details
                 name: snippets-stage-secrets
           - name: DEBUG
             value: "False"
           - name: ENABLE_ADMIN
             value: "True"
           - name: ENFORCE_HOST
             value: "snippets.allizom.org"
           - name: FILE_STORAGE
             value: snippets.base.storage.S3Storage
           - name: K8S_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: K8S_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: NEW_RELIC_APP_NAME
             value: snippets-stage-oregon-a
           - name: NEW_RELIC_LICENSE_KEY
             valueFrom:
               secretKeyRef:
                 key: new-relic-license-key
                 name: snippets-stage-secrets
           - name: OIDC_ENABLE
             value: "True"
           - name: OIDC_OP_AUTHORIZATION_ENDPOINT
             value: https://auth.mozilla.auth0.com/authorize
           - name: OIDC_OP_TOKEN_ENDPOINT
             value: https://auth.mozilla.auth0.com/oauth/token
           - name: OIDC_OP_USER_ENDPOINT
             value: https://auth.mozilla.auth0.com/userinfo
           - name: OIDC_RP_CLIENT_ID
             valueFrom:
               secretKeyRef:
                 key: oidc-rp-client-id
                 name: snippets-stage-secrets
           - name: OIDC_RP_CLIENT_SECRET
             valueFrom:
               secretKeyRef:
                 key: oidc-rp-client-secret
                 name: snippets-stage-secrets
           - name: PROD_DETAILS_STORAGE
             value: product_details.storage.PDDatabaseStorage
           - name: SECRET_KEY
             valueFrom:
               secretKeyRef:
                 key: secret-key
                 name: snippets-stage-secrets
           - name: SECURE_BROWSER_XSS_FILTER
             value: "True"
           - name: SECURE_CONTENT_TYPE_NOSNIFF
             value: "True"
           - name: SECURE_HSTS_SECONDS
             value: "31536000"
           - name: SECURE_SSL_REDIRECT
             value: "True"
           - name: SENTRY_DSN
             valueFrom:
               secretKeyRef:
                 key: sentry-dsn
                 name: snippets-stage-secrets
           - name: SENTRY_ENVIRONMENT
             value: stage
           - name: SITE_HEADER
             value: Snippets Administration Staging
           - name: SITE_TITLE
             value: Mozilla Snippets Staging Admin
           - name: SITE_URL
             value: https://snippets.allizom.org
           - name: SLACK_ENABLE
             value: "True"
           - name: SLACK_WEBHOOK
             valueFrom:
               secretKeyRef:
                 key: slack-webhook
                 name: snippets-stage-secrets
           - name: SNIPPET_BUNDLE_TIMEOUT
             value: "1800"
           - name: SNIPPET_HTTP_MAX_AGE
             value: "600"
           - name: WSGI_KEEP_ALIVE
             value: "90"
           - name: WSGI_NUM_WORKERS
             value: "2"
           - name: CDN_URL
             value: https://d177vs5g6znz6f.cloudfront.net
           - name: MEDIA_BUNDLES_ROOT
             value: us-west/bundles/
           - name: MEDIA_ICONS_ROOT
             value: media/icons/
           - name: MEDIA_BUNDLES_PREGEN_ROOT
             value: us-west/bundles-pregen/
           - name: RATELIMIT_ENABLE
             value: "True"
        image: mozmeao/snippets:16fc02b8
        imagePullPolicy: IfNotPresent
        name: snippets-stage
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /healthz/
            scheme: HTTP
            port: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 600Mi
          requests:
            cpu: 250m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
